"""
Django settings for cloth_system project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages

# 加载项目根目录.env环境变量（无 .env 文件时不引爆）
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 自动创建日志文件夹，防止启动500报错
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-replace-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# 允许访问的主机（生产环境通过 .env 的 DJANGO_ALLOWED_HOSTS 配置公网域名）
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'order',
]

MIDDLEWARE = [
    'order.middleware.RequestLogContextMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 会话超时中间件：已注释停用，后续需要时取消本行注释
    # 'order.middleware.SessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cloth_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 会话超时前端配置：与中间件一起停用
                # 'order.context_processors.session_security',
            ],
        },
    },
]

WSGI_APPLICATION = 'cloth_system.wsgi.application'


# Database
# 有环境变量配置 MySQL 时用 MySQL，否则自动降级用 SQLite 方便本地开发
DB_NAME = os.getenv("DB_NAME")

if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': os.getenv("DB_USER"),
            'PASSWORD': os.getenv("DB_PASSWORD"),
            'HOST': os.getenv("DB_HOST", "127.0.0.1"),
            'PORT': os.getenv("DB_PORT", "3306"),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'connect_timeout': 10,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# 缓存配置：有 REDIS_URL 就用 Redis（生产环境），否则用本地内存（开发环境）
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
# 收集静态文件输出目录
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django messages to Bootstrap alert mapping
MESSAGE_TAGS = {
    messages.ERROR: "danger",
    messages.WARNING: "warning",
    messages.SUCCESS: "success",
    messages.INFO: "info",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name}:{lineno} [用户:{username} IP:{ip}] {message}",
            "style": "{",
        },
    },
    "filters": {
        "request_context": {
            "()": "order.logging_context.RequestContextFilter",
        },
    },
    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django-error.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["request_context"],
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_context"],
        },
        "info_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django-info.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["request_context"],
        },
    },
    "loggers": {
        "order": {
            "handlers": ["file", "info_file", "console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Authentication settings
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ===================== 会话超时安全设置 =====================
# 当前功能已注释停用；重新启用时恢复 MIDDLEWARE、context processor、views/templates 中的注释即可
# 供应商 / 超管账户空闲超时（分钟），0 表示不启用
SUPPLIER_SESSION_IDLE_TIMEOUT_MINUTES = int(os.environ.get("SUPPLIER_SESSION_IDLE_TIMEOUT_MINUTES", "30"))
SUPERUSER_SESSION_IDLE_TIMEOUT_MINUTES = int(os.environ.get("SUPERUSER_SESSION_IDLE_TIMEOUT_MINUTES", "15"))
SESSION_TIMEOUT_WARNING_SECONDS = int(os.environ.get("SESSION_TIMEOUT_WARNING_SECONDS", "60"))

# Nginx 健康探测地址（生产环境通过 .env 的 NGINX_CHECK_URL 配置公网地址；未配置时监控页显示"未配置"）
NGINX_CHECK_URL = os.environ.get("NGINX_CHECK_URL", "http://127.0.0.1:8000/")

# ===================== FRP HTTPS穿透兼容 =====================
# 信任FRP外网HTTPS地址，提交表单不报400/403
# CSRF 可信来源：写死，不依赖 .env（本地开发 + 生产 FRP 公网地址）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://nas.u737912.nyat.app:40614",
    "https://frp-ski.com:40614",
]

# 代理转发请求头兼容（生产环境启用，本地开发可注释）
# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HTTPS Cookie 安全配置（生产环境启用，本地 HTTP 开发需注释）
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
