# Generated by Django 5.2.14 on 2026-06-01 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('customer_address', models.TextField(verbose_name='客户地址')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已送达'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('unpaid', '未支付'), ('partial', '部分支付'), ('paid', '已支付'), ('refunded', '已退款')], default='unpaid', max_length=20, verbose_name='支付状态')),
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='发货日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编码')),
                ('size', models.CharField(max_length=20, verbose_name='尺码')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
            },
        ),
    ]
