# Generated by Django 5.2.14 on 2026-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_order_clothorder_delete_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='certificate_status',
            field=models.CharField(blank=True, choices=[('invoiced', '已开票'), ('not_invoiced', '未开票')], max_length=20, verbose_name='是否开证'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='cloth_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='布种'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='customer',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='finished_product_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成品成本价格'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='finished_product_supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='成品供应商'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='finished_product_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成品出货对账总金额'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('invoiced', '已开票'), ('not_invoiced', '未开票')], max_length=20, verbose_name='是否开票'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='订单数量'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('bulk', '大货订单'), ('bulk_print', '大货-印花'), ('sample', '样品订单'), ('other', '其他')], max_length=20, verbose_name='订单类似'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='overdue_status',
            field=models.CharField(blank=True, choices=[('overdue', '逾期'), ('not_overdue', '未逾期')], max_length=20, verbose_name='是否逾期'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('before_delivery', '货前'), ('after_delivery', '货后'), ('partial', '部分支付')], max_length=20, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', '已付款'), ('unpaid', '未付款'), ('partial', '部分支付')], max_length=20, verbose_name='是否付款'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='textile_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='纺织类型'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='total_shipment_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='出货总数量'),
        ),
    ]
