# Generated by Django 5.2.14 on 2026-06-03 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_clothorder_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(max_length=100, verbose_name='布种')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('color_code', models.CharField(blank=True, max_length=50, verbose_name='色号')),
                ('composition', models.CharField(blank=True, max_length=100, verbose_name='成份')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='门幅(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='克重(g/m²)')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('booth', models.CharField(blank=True, max_length=100, verbose_name='档口')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('unit', models.CharField(choices=[('kg', '公斤'), ('m', '米'), ('yard', '码'), ('pcs', '件'), ('roll', '卷')], default='kg', max_length=10, verbose_name='单位')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='单价')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['cloth_type'], name='order_i_cloth_t_2c2675_idx'), models.Index(fields=['supplier'], name='order_i_supplie_dfa700_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整')], max_length=10, verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='order.inventoryitem', verbose_name='库存品')),
            ],
            options={
                'verbose_name': '库存记录',
                'verbose_name_plural': '库存记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
