# Generated by Django 5.2.14 on 2026-06-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_update_inventoryitem_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整')], max_length=10, verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存记录',
                'verbose_name_plural': '库存记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='clothorder',
            new_name='order_cloth_serial__96b5be_idx',
            old_name='order_c_serial__0660f1_idx',
        ),
        migrations.RenameIndex(
            model_name='clothorder',
            new_name='order_cloth_custome_c4e087_idx',
            old_name='order_c_custome_fff952_idx',
        ),
        migrations.RenameIndex(
            model_name='clothorder',
            new_name='order_cloth_order_d_7d60ab_idx',
            old_name='order_c_order_d_10cfac_idx',
        ),
        migrations.RenameIndex(
            model_name='clothorder',
            new_name='order_cloth_payment_d584ef_idx',
            old_name='order_c_payment_e70eeb_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='order_inven_cloth_n_ecabc6_idx',
            old_name='order_inv_cloth_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='order_inven_custome_f6cd78_idx',
            old_name='order_inv_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='order_inven_quantit_5fe5ce_idx',
            old_name='order_inv_qty_idx',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='order.inventoryitem', verbose_name='库存品'),
        ),
    ]
