# Generated by Django 5.2.14 on 2026-06-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_inventorylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='order.inventoryitem'),
        ),
    ]
