# Generated by Django 5.2.14 on 2026-07-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_inventorylog_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='布种编号')),
                ('cloth_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='材料名称')),
                ('cloth_type', models.CharField(blank=True, max_length=100, verbose_name='布种类型')),
                ('customer', models.CharField(blank=True, max_length=100, verbose_name='客户')),
                ('composition_cn', models.CharField(blank=True, max_length=200, verbose_name='成份（中文）')),
                ('composition_en', models.CharField(blank=True, max_length=200, verbose_name='成份（英文）')),
                ('width', models.CharField(blank=True, max_length=50, verbose_name='可裁门幅')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='克重GSM')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('density', models.CharField(blank=True, max_length=200, verbose_name='密度')),
                ('process_cn', models.TextField(blank=True, verbose_name='加工工艺（中文）')),
                ('process_en', models.TextField(blank=True, verbose_name='加工工艺（英文）')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('supplier1', models.CharField(blank=True, max_length=100, verbose_name='一级供应商')),
                ('supplier2', models.CharField(blank=True, max_length=100, verbose_name='二级供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '布种编号',
                'verbose_name_plural': '布种编号',
                'ordering': ['cloth_code'],
                'indexes': [models.Index(fields=['cloth_code'], name='order_cloth_cloth_c_c965c9_idx'), models.Index(fields=['cloth_name'], name='order_cloth_cloth_n_1706f4_idx'), models.Index(fields=['cloth_type'], name='order_cloth_cloth_t_c5d3b0_idx')],
            },
        ),
    ]
