# Generated by Django 5.2.14 on 2026-07-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_clothcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothcatalog',
            name='supplier1_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商编号'),
        ),
    ]
