# Generated by Django 5.2.14 on 2026-07-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_clothcatalog_supplier1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='progress_current',
            field=models.IntegerField(default=0, verbose_name='当前进度'),
        ),
        migrations.AddField(
            model_name='clothorder',
            name='progress_stages',
            field=models.TextField(blank=True, default='["客户下单","通知供应商","大货样","批色","查布","发货","待收款","已完成"]', verbose_name='进度阶段'),
        ),
    ]
