# Generated by Django 5.2.15 on 2026-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_clothorder_progress_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='订单号'),
        ),
    ]
