# Generated by Django 5.2.15 on 2026-07-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_clothorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('bulk', '大货订单'), ('bulk_print', '大货-印花'), ('sample', '样品订单'), ('other', '其他')], max_length=20, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='textile_type',
            field=models.CharField(blank=True, choices=[('woven', '梭织布'), ('knit', '针织布')], default='woven', max_length=50, verbose_name='纺织类型'),
        ),
    ]
