# Generated by Django 5.2.14 on 2026-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_supplier_clothorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
