# Generated by Django 5.2.14 on 2026-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_clothorder_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='地址'),
        ),
    ]
