# Generated by Django 5.2.14 on 2026-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_clothorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='supplier_shipped',
            field=models.BooleanField(default=False, verbose_name='供应商已出货'),
        ),
    ]
