# Generated by Django 5.2.14 on 2026-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_clothorder_supplier_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='supplier_paid',
            field=models.BooleanField(default=False, verbose_name='已付款给供应商'),
        ),
    ]
