# Generated by Django 5.2.14 on 2026-07-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_supplier_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothorder',
            name='knitted_fabric_shipment_weight',
        ),
    ]
