# Generated by Django 5.2.14 on 2026-07-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_clothorder_supplier_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothorder',
            name='color_code',
        ),
    ]
