# Generated by Django 5.2.14 on 2026-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_clothorder_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='色号'),
        ),
    ]
