# Generated by Django 5.2.14 on 2026-07-24 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_clothorder_color_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(default=1, verbose_name='批次号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='出货日期')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='出货数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order.clothorder', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '出货记录',
                'verbose_name_plural': '出货记录',
                'ordering': ['order', 'batch_number'],
                'indexes': [models.Index(fields=['order', 'batch_number'], name='order_shipm_order_i_2048a2_idx')],
            },
        ),
    ]
