# Generated by Django 5.2.14 on 2026-07-24 21:11

from django.db import migrations


def migrate_shipment_data(apps, schema_editor):
    ClothOrder = apps.get_model('order', 'ClothOrder')
    Shipment = apps.get_model('order', 'Shipment')
    User = apps.get_model('auth', 'User')

    # Try to find an admin user as default creator
    default_user = User.objects.filter(is_superuser=True).first()

    total = created = 0
    for order in ClothOrder.objects.all():
        for i in range(1, 6):
            date_field = f'finished_product_shipment_date_{i}'
            qty_field = f'finished_product_shipment_quantity_{i}'
            date = getattr(order, date_field, None)
            qty = getattr(order, qty_field, None)
            if date or qty:
                Shipment.objects.create(
                    order=order,
                    batch_number=i,
                    date=date,
                    quantity=qty,
                    created_by=default_user,
                )
                created += 1
        total += 1

    if total:
        print(f"Migrated {created} shipment records across {total} orders")


def reverse_migration(apps, schema_editor):
    Shipment = apps.get_model('order', 'Shipment')
    Shipment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_shipment'),
    ]

    operations = [
        migrations.RunPython(migrate_shipment_data, reverse_migration),
    ]
