# Generated by Django 5.2.14 on 2026-07-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
