# Generated by Django 5.2.14 on 2026-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_shipment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='supplier_remark',
            field=models.TextField(blank=True, default='', verbose_name='备注给供应商'),
        ),
    ]
