# Generated by Django 5.2.14 on 2026-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_clothorder_supplier_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='customer',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='clothorder',
            name='finished_product_supplier',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='成品供应商'),
        ),
    ]
