# Generated by Django 5.2.15 on 2026-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_clothorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='style_number',
            field=models.TextField(blank=True, verbose_name='款号'),
        ),
    ]
