# Generated by Django 5.2.14 on 2026-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_clothorder_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Excel??')),
                ('date_sent', models.DateField(blank=True, null=True, verbose_name='????')),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='???')),
                ('supplier_contact', models.TextField(blank=True, verbose_name='???/??')),
                ('gfg_dev_no', models.CharField(blank=True, max_length=100, verbose_name='GFG???')),
                ('preferred_material', models.CharField(blank=True, max_length=100, verbose_name='????')),
                ('color_card', models.CharField(blank=True, max_length=50, verbose_name='??')),
                ('article_no', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='????')),
                ('composition', models.TextField(blank=True, verbose_name='??')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='??')),
                ('cuttable_width', models.CharField(blank=True, max_length=50, verbose_name='??')),
                ('price_200m_text', models.TextField(blank=True, verbose_name='200?????')),
                ('price_200m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200???-??')),
                ('price_200m_print', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200???-??')),
                ('price_200m_unit', models.CharField(blank=True, default='M', max_length=10, verbose_name='????')),
                ('regular_mcq', models.CharField(blank=True, max_length=100, verbose_name='?????')),
                ('price_regular_text', models.TextField(blank=True, verbose_name='??????')),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='????-??')),
                ('price_regular_print', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='????-??')),
                ('price_regular_unit', models.CharField(blank=True, default='M', max_length=10, verbose_name='??????')),
                ('lead_time', models.CharField(blank=True, max_length=100, verbose_name='??')),
                ('price_validity', models.CharField(blank=True, max_length=100, verbose_name='?????')),
                ('yarn_count', models.CharField(blank=True, max_length=100, verbose_name='??')),
                ('density_gauge', models.CharField(blank=True, max_length=100, verbose_name='??/??')),
                ('remark', models.TextField(blank=True, verbose_name='??')),
                ('quoted_to', models.CharField(blank=True, max_length=200, verbose_name='???')),
                ('extra_remark', models.TextField(blank=True, verbose_name='????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-date_sent', 'article_no'],
                'indexes': [models.Index(fields=['article_no'], name='order_fabri_article_78ad3e_idx'), models.Index(fields=['supplier_name'], name='order_fabri_supplie_79249f_idx')],
            },
        ),
    ]
