# Generated by Codex - make row_index non-unique
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_fabricquotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricquotation',
            name='row_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Excel行号'),
        ),
    ]
