# Generated by Django 5.2.15 on 2026-07-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_clothorder_style_number'),
        ('order', '0032_auto_20260727_1503'),
    ]

    operations = [
    ]
