# Generated by Django 5.2.15 on 2026-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_merge_20260727_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='style_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='款号'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='row_index',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Excel??'),
        ),
    ]
