# Generated by Django 5.2.14 on 2026-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_clothorder_style_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricquotation',
            options={'ordering': ['-date_sent', 'article_no'], 'verbose_name': '面料报价', 'verbose_name_plural': '面料报价'},
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='article_no',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='面料编号'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='color_card',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='composition',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='导入时间'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='cuttable_width',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='date_sent',
            field=models.DateField(blank=True, null=True, verbose_name='导入时间'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='density_gauge',
            field=models.CharField(blank=True, max_length=100, verbose_name='密度/针数'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='extra_remark',
            field=models.TextField(blank=True, verbose_name='附加备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='gfg_dev_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='GFG开发号'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='lead_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='preferred_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='附加备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_200m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200米价格-素色'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_200m_print',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200米价格-印花'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_200m_text',
            field=models.TextField(blank=True, verbose_name='200米价格原文'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_200m_unit',
            field=models.CharField(blank=True, default='M', max_length=10, verbose_name='价格单位'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_regular',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='常规价格-素色'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_regular_print',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='常规价格-印花'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_regular_text',
            field=models.TextField(blank=True, verbose_name='常规价格原文'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_regular_unit',
            field=models.CharField(blank=True, default='M', max_length=10, verbose_name='常规价格单位'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='price_validity',
            field=models.CharField(blank=True, max_length=100, verbose_name='报价有效期'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='quoted_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='报价给'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='regular_mcq',
            field=models.CharField(blank=True, max_length=100, verbose_name='报价有效期'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='supplier_contact',
            field=models.TextField(blank=True, verbose_name='联系人/邮箱'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='supplier_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fabricquotation',
            name='yarn_count',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
    ]
