# Generated by Django 5.2.15 on 2026-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_clothorder_style_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='style_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='款号'),
        ),
    ]
