# Generated by Django 5.2.15 on 2026-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_clothorder_style_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothorder',
            name='style_number',
            field=models.TextField(blank=True, verbose_name='款号'),
        ),
    ]
