# Generated by Django 5.2.14 on 2026-09-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0037_alter_fabricquotation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="客户名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="客户编号"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="order_custo_name_84b743_idx"),
                    models.Index(fields=["code"], name="order_custo_code_667686_idx"),
                ],
            },
        ),
    ]
