# Generated by Django 5.2.15 on 2026-07-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_fabricquotation_options_and_more'),
        ('order', '0037_alter_fabricquotation_options_and_more'),
    ]

    operations = [
    ]
