# Generated by Django 5.2.15 on 2026-09-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_clothorder_style_number'),
        ('order', '0038_customer'),
        ('order', '0038_merge_20260731_0000'),
    ]

    operations = [
    ]
